#!/usr/bin/env php
<?php

include 'src/Dates/BirthDays.php';

$birthDate = "1987-10-14";
$days = new \LigaDzi\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";
