#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$birthDate = "1987-10-14";
$days = new \LigaDzi\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays\n";
